/*

Kth Symbol in Grammar: 
    The Kth Symbol in Grammar problem is a classic recursion problem that involves generating a specific symbol in a binary grammar sequence. The grammar is defined as follows:
        - Start with "0" as the first row (row 1).
        - Each subsequent row is generated by replacing each "0" with "01" and each "1" with "10".

For example:
    Row 1: 0
    Row 2: 01
    Row 3: 0110
    Row 4: 01101001
    and so on.

The task is to find the Kth symbol in the Nth row of this grammar.

To solve this problem using recursion, we can observe that:
    - The first half of any row is derived from the previous row.
    - The second half of any row is the complement of the first half.

Using this observation, we can define a recursive function to find the Kth symbol in the Nth row.

Here is a JavaScript implementation of the solution:function kthSymbolInGrammar(N, K) {
  // Base case: the first row has only one symbol '0'
  if (N === 1) {
    return 0;
  }

  // Calculate the length of the previous row
  const mid = Math.pow(2, N - 1) / 2;

  // If K is in the first half, it is the same as in the previous row
  if (K <= mid) {
    return kthSymbolInGrammar(N - 1, K):
  } else {
    // If K is in the second half, it is the complement of the corresponding symbol in the previous row
    return 1 - kthSymbolInGrammar(N - 1, K - mid);
  }


Complexity Analysis:
    - Time Complexity: O(N), where N is the row number. In the worst case, we may have to recurse N times.
    - Space Complexity: O(N) due to the recursion stack.
*/

function kthSymbolInGrammar(N, K) {
  // Base case: the first row has only one symbol '0'
  if (N === 1) {
    return 0;
  }

  // Calculate the length of the previous row
  const mid = Math.pow(2, N - 1) / 2;

  // If K is in the first half, it is the same as in the previous row
  if (K <= mid) {
    return kthSymbolInGrammar(N - 1, K);
  } else {
    // If K is in the second half, it is the complement of the corresponding symbol in the previous row
    return 1 - kthSymbolInGrammar(N - 1, K - mid);
  }
}

// Example usage:
console.log(kthSymbolInGrammar(4, 5)); // Output: 1
console.log(kthSymbolInGrammar(3, 3)); // Output: 1
console.log(kthSymbolInGrammar(2, 2)); // Output: 1


// ShortHand:
function kthGrammar(n, k){
    if(n == 1) return 0;
    if(k <= 2**(n-2)){
        return kthGrammar(n-1, k);
    }else{
        return 1 - kthGrammar(n-1, k - 2**(n-2));
    }
}